.TH NCPING 1 "January 2024" "Version 1.3" "User Commands"

.SH NAME
ncping \- Periodically ping hosts and manage configuration

.SH SYNOPSIS
.B ncping
[\fIOPTIONS\fR] [\fIcommand\fR [\fIarguments\fR]]

.SH DESCRIPTION
\fBncping\fR is a script that periodically pings specified hosts and provides functionality to manage host groups, cron jobs, and configuration.

.PP
The script can be executed with various commands and options to perform specific tasks.

.SH COMMANDS
The following commands are available:

.IP "\fBconfig\fR"
Opens the configuration file for editing.

.IP "\fBaddhost\fR \fIIP-ADDRESS\fR"
Adds the specified IP address to the list of hosts.

.IP "\fBdelhost\fR \fIIP-ADDRESS\fR"
Removes the specified IP address from the list of hosts.

.IP "\fB-l\fR"
Lists all IP addresses (hosts).

.IP "\fBccron\fR \fICRON-SCHEDULE\fR"
Creates a cron job for periodic pinging based on the specified cron schedule.

.IP "\fBdelcron\fR \fICRON-JOB-NAME\fR"
Deletes the cron job with the specified name.

.SH OPTIONS
The following options are available:

.IP "\fB-h\fR"
Display this help message.

.IP "\fBlog\fR"
Opens the log file for viewing and editing.

.SH EXAMPLES
To add a host:
.B ncping addhost 192.168.1.1

To create a cron job:
.B ncping ccron "*/5"

To delete a cron job:
.B ncping delcron mycronjob

.SH SEE ALSO
.BR cron (8),
.BR ping (8)

.SH AUTHOR
Written by Samuel Lindenfelser.

.SH COPYRIGHT
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

.SH BUGS
Report bugs to my Github.

.SH VERSION
1.3

.SH DATE
January 2024
